### ISSUE TITLE
Multiple Primary Targets not yet managed

### ISSUE THREAD

**Issue by ebrassfieldbourke** [uksrc/emerlin2caom#18]
This is a reminder to address this for caom2.5 refactor, as we are currently collecting the primary target from the text generated from a pickle file, and if there is more than one primary target, it shows up as a string, i.e.
`0811+2449,1056+4146,1433+4842,1436+4928`
When the casatools tries to then use the value of the primary target to collect the RA and Dec from the Measurement Set, it causes an eventual RuntimeError because the 'field name' is unknown.  
Requirement for code to discern whether target is comma-delimited or not, and if so, separate into multiple targets for which RA and Dec will be collected, and for which each a Plane (and possibly Derived Observation?) would be generated.  Which target is selected for the Simple Observation or Derived Observation as the primary target is yet to be determined.  

> 2024-12-11 10:56:07	INFO	MSMetaData::_computeScanAndSubScanProperties 	Computing scan and subscan properties...
> 2024-12-11 10:56:08	SEVERE	msmetadata_cmpt.cc::scansforfield	Exception Reported: Exception: Unknown field name 0811+2449,1056+4146,1433+4842,1436+4928.
> 2024-12-11 10:56:08	SEVERE	msmetadata_cmpt.cc::scansforfield+	... thrown by std::set<Int> casa6core::MSMetaData::getFieldIDsForField(const casa6core::String &) const at File: casacore/ms/MSOper/MSMetaData.cc, line: 2516
> Traceback (most recent call last):
>   File "run_script.py", line 4, in <module>
>     a.build_metadata()
>   File "/Users/user/repos/emerlin2caom-uploading_in_python/emerlin2caom2/main_app.py", line 290, in build_metadata
>     casa_info = casa.msmd_collect(self.ms_dir_main, pickle_obj['targets'])
>   File "/Users/user/repos/emerlin2caom-uploading_in_python/emerlin2caom2/casa_reader.py", line 44, in msmd_collect
>     'num_scans': len(msmd.scansforfield(targ_name)),
>   File "/Users/user/miniconda3/envs/py38/lib/python3.8/site-packages/casatools/msmetadata.py", line 548, in scansforfield
>     return self._swigobj.scansforfield(_any_ec(field), obsid, arrayid)
>   File "/Users/user/miniconda3/envs/py38/lib/python3.8/site-packages/casatools/__casac__/msmetadata.py", line 2366, in scansforfield
>     return _msmetadata.msmetadata_scansforfield(self, *args, **kwargs)
> RuntimeError: Exception: Unknown field name 0811+2449,1056+4146,1433+4842,1436+4928.
> ... thrown by std::set<Int> casa6core::MSMetaData::getFieldIDsForField(const casa6core::String &) const at File: casacore/ms/MSOper/MSMetaData.cc, line: 2516

**Comment by ebrassfieldbourke** [comment]
On further investigation, this is definitely an **unfulfilled use case Issue**.
CAOM only allows for one Target, TargetPosition, and all metadata for a single science target. 
Currently, our code will select this target from the inputs.ini, and casatools collects the relevant information (RA,Dec) from the FIELD for that target (measurement set language for a target).  
However, as an astronomer, I want to search for an RA/Dec position, and get a list of observations returned that satisfy this position (and range/cone-search).  The RA/Dec that is connected to each CAOM Observation Object (and nested Planes and Artifacts) is the RA/Dec for the aforementioned single target source.  If there are two or more science targets (not just ancillary/calibrator), as we've now come across in several e-MERLIN data sets, and as we know is not uncommon in interferometric observations, an RA/Dec cone-style search will not return any Observation where the desired target/RA/Dec were not the one that happened to be collected for CAOM. 
One work-around is to create a derived Observation for each science target, if more than one science target exists.  The problem then is that the model is no longer representing reality, and very much metadata will be duplicated via the nested Planes/Artifacts.  
The other option, which to me makes the most sense, is for CAOM to allow more than one primary science target for an Observation.  This way, a cone search for RA/Dec close to any/either science target will return the relevant Observation, rather than information loss.  More investigation is needed to determine what impact this will have on inherited elements for the nested Planes/Artifacts.

**Comment by ebrassfieldbourke** [comment]
As an aside, ObsCore also has a 0-1 multiplicity for their ObsDataSet.Target element.  Perhaps data models designed for fits generally are not going to work for measurement sets.  
ALMA??

**Comment by ebrassfieldbourke** [comment]
> ... The other option, which to me makes the most sense, is for CAOM to allow more than one primary science target for an Observation. This way, a cone search for RA/Dec close to any/either science target will return the relevant Observation, rather than information loss. More investigation is needed to determine what impact this will have on inherited elements for the nested Planes/Artifacts.

From Pat Dowler via Slack conversation:  The cardinality of observation->target is 0..1 so it is optional, but one target. That works for a lot of data, but not so well for radio data. As a data discovery model intended to be exposed via TAP queries, there are good reasons for that limitation (and others like it)... but I'll leave that aside for now.

**Comment by ebrassfieldbourke** [comment]
Resolved in latest version of emerlin2caom by interpreting each target as a Simple Observation in CAOM.
